### ISSUE TITLE
[Bug] vllm-openvino docker image build fail

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#1202]
### Priority

P2

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source
- [ ] Other

### Running nodes

Single Node

### Description
third_parities/vllm-openvino docker image build fail 
```
  vllm-openvino:
    build:
      context: vllm-openvino
      dockerfile: Dockerfile.openvino
    image: ${REGISTRY:-opea}/vllm-openvino:${TAG:-latest}
```
Job links: 
https://github.com/opea-project/GenAIComps/actions/runs/12902860130/job/35977143316?pr=1176
