### ISSUE TITLE
[Bug] Docker image guardrails-hallucination-detection build fail

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#1204]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source
- [ ] Other

### Deploy method

- [x] Docker
- [x] Docker Compose
- [ ] Kubernetes Helm Charts
- [ ] Other

### Running nodes

Single Node

### What's the version?

53fcc6ff112faa7f20ce59eaf23ec93e397fcb2f

### Description

guardrails-hallucination-detection docker image build fail
```
guardrails-hallucination-detection:
    build:
      dockerfile: comps/guardrails/src/hallucination_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-hallucination-detection:${TAG:-latest}
```
Job link: https://github.com/opea-project/GenAIComps/actions/runs/12900670469/job/35971526507#step:5:3927

### Reproduce steps

 docker compose build  --no-cache .github/workflows/docker/compose/guardrails-compose.yaml

### Raw log

```shell

```
