### ISSUE TITLE
[Bug]gpt-sovits  docker image build fail

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#1205]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source
- [ ] Other

### Deploy method

- [x] Docker
- [x] Docker Compose
- [ ] Kubernetes Helm Charts
- [ ] Other

### Running nodes

Single Node

### What's the version?

53fcc6ff112faa7f20ce59eaf23ec93e397fcb2f

### Description

gpt-sovits docker image build fail
```
  gpt-sovits:
    build:
      dockerfile: comps/tts/src/integrations/dependency/gpt-sovits/Dockerfile
    image: ${REGISTRY:-opea}/gpt-sovits:${TAG:-latest}
```
Job link: https://github.com/opea-project/GenAIComps/actions/runs/12900670469/job/35971530295#step:5:6739

![Image](https://github.com/user-attachments/assets/d6e3158f-0d44-450b-83a8-a717c363a330)

### Reproduce steps

 docker compose build  --no-cache .github/workflows/docker/compose/tts-compose.yaml
### Raw log

```shell

```
