### ISSUE TITLE
[Bug] lvm-video-llama docker image build fail

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#1206]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source
- [ ] Other

### Deploy method

- [x] Docker
- [x] Docker Compose
- [ ] Kubernetes Helm Charts
- [ ] Other

### Running nodes

Single Node

### What's the version?

53fcc6ff112faa7f20ce59eaf23ec93e397fcb2f

### Description

 lvm-video-llama docker image build fail
```
  lvm-video-llama:
    build:
      dockerfile: comps/lvms/src/integrations/dependency/video-llama/Dockerfile
    image: ${REGISTRY:-opea}/lvm-video-llama:${TAG:-latest}
```
Job link: https://github.com/opea-project/GenAIComps/actions/runs/12900670469/job/35971527833#step:5:2964

![Image](https://github.com/user-attachments/assets/8bec5209-38d6-4069-8092-5419207dce57)

### Reproduce steps

 docker compose build  --no-cache .github/workflows/docker/compose/lvms-compose.yaml

### Raw log

```shell

```
