### ISSUE TITLE
[Bug] llm-eval docker image build fail

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#1207]
### Priority

P2

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source
- [ ] Other

### Deploy method

- [x] Docker
- [x] Docker Compose
- [ ] Kubernetes Helm Charts
- [ ] Other

### Running nodes

Single Node

### What's the version?

53fcc6ff112faa7f20ce59eaf23ec93e397fcb2f

### Description

llm-eval docker image build fail
```
  llm-eval:
    build:
      dockerfile: comps/llms/utils/lm-eval/Dockerfile
    image: ${REGISTRY:-opea}/llm-eval:${TAG:-latest}
```
Job link: https://github.com/opea-project/GenAIComps/actions/runs/12900670469/job/35971527475#step:5:3823

![Image](https://github.com/user-attachments/assets/71b7f74e-cfb8-432a-81d3-675c7d872736)

### Reproduce steps

 docker compose build  --no-cache .github/workflows/docker/compose/llms-compose.yaml

### Raw log

```shell

```
