### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#260]

**Comment by eero-t** [comment]
Checked the 9 ChatQnA services and all of them provide some metrics from their `/metrics` endpoint.

For the services using images built from OPEA `Dockerfiles`, those are just the basic container and Python metrics, which aren't very interesting.

TGI and TEI services using HuggingFace images provide nice set of relevant inferencing metrics though.

Getting Prometheus to scrape TGI service is easy.  One needs to add label to the service file that Prometheus `serviceMonitor` can catch:
```
--- a/ChatQnA/kubernetes/manifests/tgi_service.yaml
+++ b/ChatQnA/kubernetes/manifests/tgi_service.yaml
@@ -67,6 +67,8 @@ kind: Service
 apiVersion: v1
 metadata:
   name: tgi-svc
+  labels:
+    svc: tgi-svc
 spec:
   type: ClusterIP
   selector:
```

And add `serviceMonitor` telling Prometheus to scrape that service at suitable interval:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tgi-svc
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      svc: tgi-svc
  endpoints:
  - interval: 8s
    port: service
    scheme: http
```

Prometheus operator will pick up the applied `serviceMonitor`(s), and update Prometheus deployment's configuration accordingly.

One can see config having been updated when `tgi-svc` appears as Prometheus scraping target in its GUI, and in Prometheus metrics:
```
$ prom_url=$(kubectl -n monitoring get services|awk '/^prometheus-k8s/{printf("%s:%s",$3,$5)}'|cut -d/ -f1)
$ curl --no-progress-meter $prom_url/metrics | grep scrape_pool_targets.*tgi-svc
prometheus_target_scrape_pool_targets{scrape_job="serviceMonitor/default/tgi-svc/0"} 0
```

(If Prometheus can scrape service instance(s), metric value for `tgi-svc/0` target  is non-zero.)

There's a very nice Grafana dashboard to show the provided TGI metrics:  https://grafana.com/grafana/dashboards/19831-text-generation-inference-dashboard/

It should be straightforward to apply same also for the "ChatQnA" TEI embedding and reranking services, their metric names just start with `te_` instead of `tgi_`.

Note: by default Prometheus has RBAC rules for accessing just `monitoring`, `kube-system` and `default` namespaces.  If services are somewhere else, also Prometheus RBAC rules would need to be updated to include other relevant namespaces.
